"""Add creator for a group

Revision ID: 23fe42a8bfbd
Revises: 19c6a424755b
Create Date: 2023-05-12 17:37:02.140811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fe42a8bfbd'
down_revision = '19c6a424755b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
